# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gymmasssorla/Desktop/grizzly

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gymmasssorla/Desktop/grizzly

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gymmasssorla/Desktop/grizzly/CMakeFiles /home/gymmasssorla/Desktop/grizzly/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gymmasssorla/Desktop/grizzly/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named grizzly

# Build rule for target.
grizzly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grizzly
.PHONY : grizzly

# fast build rule for target.
grizzly/fast:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/build
.PHONY : grizzly/fast

src/ast/ast_dump.o: src/ast/ast_dump.c.o

.PHONY : src/ast/ast_dump.o

# target to build an object file
src/ast/ast_dump.c.o:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/ast/ast_dump.c.o
.PHONY : src/ast/ast_dump.c.o

src/ast/ast_dump.i: src/ast/ast_dump.c.i

.PHONY : src/ast/ast_dump.i

# target to preprocess a source file
src/ast/ast_dump.c.i:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/ast/ast_dump.c.i
.PHONY : src/ast/ast_dump.c.i

src/ast/ast_dump.s: src/ast/ast_dump.c.s

.PHONY : src/ast/ast_dump.s

# target to generate assembly for a file
src/ast/ast_dump.c.s:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/ast/ast_dump.c.s
.PHONY : src/ast/ast_dump.c.s

src/ast/ast_tree.o: src/ast/ast_tree.c.o

.PHONY : src/ast/ast_tree.o

# target to build an object file
src/ast/ast_tree.c.o:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/ast/ast_tree.c.o
.PHONY : src/ast/ast_tree.c.o

src/ast/ast_tree.i: src/ast/ast_tree.c.i

.PHONY : src/ast/ast_tree.i

# target to preprocess a source file
src/ast/ast_tree.c.i:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/ast/ast_tree.c.i
.PHONY : src/ast/ast_tree.c.i

src/ast/ast_tree.s: src/ast/ast_tree.c.s

.PHONY : src/ast/ast_tree.s

# target to generate assembly for a file
src/ast/ast_tree.c.s:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/ast/ast_tree.c.s
.PHONY : src/ast/ast_tree.c.s

src/ast/resolve.o: src/ast/resolve.c.o

.PHONY : src/ast/resolve.o

# target to build an object file
src/ast/resolve.c.o:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/ast/resolve.c.o
.PHONY : src/ast/resolve.c.o

src/ast/resolve.i: src/ast/resolve.c.i

.PHONY : src/ast/resolve.i

# target to preprocess a source file
src/ast/resolve.c.i:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/ast/resolve.c.i
.PHONY : src/ast/resolve.c.i

src/ast/resolve.s: src/ast/resolve.c.s

.PHONY : src/ast/resolve.s

# target to generate assembly for a file
src/ast/resolve.c.s:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/ast/resolve.c.s
.PHONY : src/ast/resolve.c.s

src/ast/types.o: src/ast/types.c.o

.PHONY : src/ast/types.o

# target to build an object file
src/ast/types.c.o:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/ast/types.c.o
.PHONY : src/ast/types.c.o

src/ast/types.i: src/ast/types.c.i

.PHONY : src/ast/types.i

# target to preprocess a source file
src/ast/types.c.i:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/ast/types.c.i
.PHONY : src/ast/types.c.i

src/ast/types.s: src/ast/types.c.s

.PHONY : src/ast/types.s

# target to generate assembly for a file
src/ast/types.c.s:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/ast/types.c.s
.PHONY : src/ast/types.c.s

src/ast/visitor.o: src/ast/visitor.c.o

.PHONY : src/ast/visitor.o

# target to build an object file
src/ast/visitor.c.o:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/ast/visitor.c.o
.PHONY : src/ast/visitor.c.o

src/ast/visitor.i: src/ast/visitor.c.i

.PHONY : src/ast/visitor.i

# target to preprocess a source file
src/ast/visitor.c.i:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/ast/visitor.c.i
.PHONY : src/ast/visitor.c.i

src/ast/visitor.s: src/ast/visitor.c.s

.PHONY : src/ast/visitor.s

# target to generate assembly for a file
src/ast/visitor.c.s:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/ast/visitor.c.s
.PHONY : src/ast/visitor.c.s

src/crash_dump.o: src/crash_dump.c.o

.PHONY : src/crash_dump.o

# target to build an object file
src/crash_dump.c.o:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/crash_dump.c.o
.PHONY : src/crash_dump.c.o

src/crash_dump.i: src/crash_dump.c.i

.PHONY : src/crash_dump.i

# target to preprocess a source file
src/crash_dump.c.i:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/crash_dump.c.i
.PHONY : src/crash_dump.c.i

src/crash_dump.s: src/crash_dump.c.s

.PHONY : src/crash_dump.s

# target to generate assembly for a file
src/crash_dump.c.s:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/crash_dump.c.s
.PHONY : src/crash_dump.c.s

src/logger.o: src/logger.c.o

.PHONY : src/logger.o

# target to build an object file
src/logger.c.o:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/logger.c.o
.PHONY : src/logger.c.o

src/logger.i: src/logger.c.i

.PHONY : src/logger.i

# target to preprocess a source file
src/logger.c.i:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/logger.c.i
.PHONY : src/logger.c.i

src/logger.s: src/logger.c.s

.PHONY : src/logger.s

# target to generate assembly for a file
src/logger.c.s:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/logger.c.s
.PHONY : src/logger.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/main.c.s
.PHONY : src/main.c.s

src/output_message.o: src/output_message.c.o

.PHONY : src/output_message.o

# target to build an object file
src/output_message.c.o:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/output_message.c.o
.PHONY : src/output_message.c.o

src/output_message.i: src/output_message.c.i

.PHONY : src/output_message.i

# target to preprocess a source file
src/output_message.c.i:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/output_message.c.i
.PHONY : src/output_message.c.i

src/output_message.s: src/output_message.c.s

.PHONY : src/output_message.s

# target to generate assembly for a file
src/output_message.c.s:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/output_message.c.s
.PHONY : src/output_message.c.s

src/parser/base_parser.o: src/parser/base_parser.c.o

.PHONY : src/parser/base_parser.o

# target to build an object file
src/parser/base_parser.c.o:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/parser/base_parser.c.o
.PHONY : src/parser/base_parser.c.o

src/parser/base_parser.i: src/parser/base_parser.c.i

.PHONY : src/parser/base_parser.i

# target to preprocess a source file
src/parser/base_parser.c.i:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/parser/base_parser.c.i
.PHONY : src/parser/base_parser.c.i

src/parser/base_parser.s: src/parser/base_parser.c.s

.PHONY : src/parser/base_parser.s

# target to generate assembly for a file
src/parser/base_parser.c.s:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/parser/base_parser.c.s
.PHONY : src/parser/base_parser.c.s

src/parser/parser.o: src/parser/parser.c.o

.PHONY : src/parser/parser.o

# target to build an object file
src/parser/parser.c.o:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/parser/parser.c.o
.PHONY : src/parser/parser.c.o

src/parser/parser.i: src/parser/parser.c.i

.PHONY : src/parser/parser.i

# target to preprocess a source file
src/parser/parser.c.i:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/parser/parser.c.i
.PHONY : src/parser/parser.c.i

src/parser/parser.s: src/parser/parser.c.s

.PHONY : src/parser/parser.s

# target to generate assembly for a file
src/parser/parser.c.s:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/parser/parser.c.s
.PHONY : src/parser/parser.c.s

src/parser/tokenizer.o: src/parser/tokenizer.c.o

.PHONY : src/parser/tokenizer.o

# target to build an object file
src/parser/tokenizer.c.o:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/parser/tokenizer.c.o
.PHONY : src/parser/tokenizer.c.o

src/parser/tokenizer.i: src/parser/tokenizer.c.i

.PHONY : src/parser/tokenizer.i

# target to preprocess a source file
src/parser/tokenizer.c.i:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/parser/tokenizer.c.i
.PHONY : src/parser/tokenizer.c.i

src/parser/tokenizer.s: src/parser/tokenizer.c.s

.PHONY : src/parser/tokenizer.s

# target to generate assembly for a file
src/parser/tokenizer.c.s:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/parser/tokenizer.c.s
.PHONY : src/parser/tokenizer.c.s

src/terminal/colours.o: src/terminal/colours.c.o

.PHONY : src/terminal/colours.o

# target to build an object file
src/terminal/colours.c.o:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/terminal/colours.c.o
.PHONY : src/terminal/colours.c.o

src/terminal/colours.i: src/terminal/colours.c.i

.PHONY : src/terminal/colours.i

# target to preprocess a source file
src/terminal/colours.c.i:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/terminal/colours.c.i
.PHONY : src/terminal/colours.c.i

src/terminal/colours.s: src/terminal/colours.c.s

.PHONY : src/terminal/colours.s

# target to generate assembly for a file
src/terminal/colours.c.s:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/terminal/colours.c.s
.PHONY : src/terminal/colours.c.s

src/terminal/styles.o: src/terminal/styles.c.o

.PHONY : src/terminal/styles.o

# target to build an object file
src/terminal/styles.c.o:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/terminal/styles.c.o
.PHONY : src/terminal/styles.c.o

src/terminal/styles.i: src/terminal/styles.c.i

.PHONY : src/terminal/styles.i

# target to preprocess a source file
src/terminal/styles.c.i:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/terminal/styles.c.i
.PHONY : src/terminal/styles.c.i

src/terminal/styles.s: src/terminal/styles.c.s

.PHONY : src/terminal/styles.s

# target to generate assembly for a file
src/terminal/styles.c.s:
	$(MAKE) -f CMakeFiles/grizzly.dir/build.make CMakeFiles/grizzly.dir/src/terminal/styles.c.s
.PHONY : src/terminal/styles.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... grizzly"
	@echo "... edit_cache"
	@echo "... src/ast/ast_dump.o"
	@echo "... src/ast/ast_dump.i"
	@echo "... src/ast/ast_dump.s"
	@echo "... src/ast/ast_tree.o"
	@echo "... src/ast/ast_tree.i"
	@echo "... src/ast/ast_tree.s"
	@echo "... src/ast/resolve.o"
	@echo "... src/ast/resolve.i"
	@echo "... src/ast/resolve.s"
	@echo "... src/ast/types.o"
	@echo "... src/ast/types.i"
	@echo "... src/ast/types.s"
	@echo "... src/ast/visitor.o"
	@echo "... src/ast/visitor.i"
	@echo "... src/ast/visitor.s"
	@echo "... src/crash_dump.o"
	@echo "... src/crash_dump.i"
	@echo "... src/crash_dump.s"
	@echo "... src/logger.o"
	@echo "... src/logger.i"
	@echo "... src/logger.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/output_message.o"
	@echo "... src/output_message.i"
	@echo "... src/output_message.s"
	@echo "... src/parser/base_parser.o"
	@echo "... src/parser/base_parser.i"
	@echo "... src/parser/base_parser.s"
	@echo "... src/parser/parser.o"
	@echo "... src/parser/parser.i"
	@echo "... src/parser/parser.s"
	@echo "... src/parser/tokenizer.o"
	@echo "... src/parser/tokenizer.i"
	@echo "... src/parser/tokenizer.s"
	@echo "... src/terminal/colours.o"
	@echo "... src/terminal/colours.i"
	@echo "... src/terminal/colours.s"
	@echo "... src/terminal/styles.o"
	@echo "... src/terminal/styles.i"
	@echo "... src/terminal/styles.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

